#cloud-config
users:
  - name: ubuntu # Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo-Regeln für diesen Benutzer
    groups: users, admin # Zugehörigkeit zu Benutzergruppen
    home: /home/ubuntu # Verzeichnis des Benutzers
    shell: /bin/bash # Standard-Shell für den Benutzer
    ssh_authorized_keys: # SSH-Schlüssel für den Benutzer
      - ssh-rsa MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjjtXld8sAqg9NNtCgJuiQgKZMz3m3CQhdP+5wTqOj5bldfsin5sT80d3Z/6f997mUL+kggG/iGs/ShrSgFD6JvAwZPZ1s73tNoWepXrxoSnst4tGhQm7He9UXUtg8Td1Hi9SWXvYyhOu3NmXN416DJhdY7k8UfhBHjPpVGzeeOCBvFCHA7YAbKA6jUpx/RRuTTxgjut8pMxVBFPu+yw1UulxeYVnu7+ovnKhDVZ3CmGN5nPYz3mNAQ4J4s9yjqQXdv0cHyVDE0XhvgpvM24xj8sR4FIBrcn9fA40HdUrvVXdcoC/AA2ULlY7WEvVYnJi4ZQ8hnQ8Q5AezTgTyd0H0QIDAQAB aws-key
ssh_pwauth: false # SSH-Passwort-Authentifizierung deaktivieren
disable_root: false # Root-Benutzer deaktivieren
package_update: true # Paketaktualisierung durchführen
packages: # Installierte Pakete
  - curl
  - wget
